// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundStore.Infrastructure;

#nullable disable

namespace SoundStore.Infrastructure.Migrations
{
    [DbContext(typeof(SoundStoreDbContext))]
    partial class SoundStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "abc",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "def",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LOA MARSHALL"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TAI NGHE MARSHALL"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PHỤ KIỆN LIFESTYLE"
                        });
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1L,
                            Url = "https://soundway.vn/wp-content/uploads/2024/10/2.png"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1L,
                            Url = "https://soundway.vn/wp-content/uploads/2024/10/major-v-two-asset-hybrid-09.png"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1L,
                            Url = "https://soundway.vn/wp-content/uploads/2024/10/major-v-two-asset-hybrid-03-lon.png"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1L,
                            Url = "https://soundway.vn/wp-content/uploads/2024/10/5-major-v-brown-lifestyle-desktop-trung-binh.png"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2L,
                            Url = "https://soundway.vn/wp-content/uploads/2021/09/Tang-ngay-01-goi-Marshall-11.png"
                        });
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SoundStore.Core.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(10)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessoriesIncluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatteryLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Connectivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequencyResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10)");

                    b.Property<string>("Sensitivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessoriesIncluded = "Cáp kết nối, túi đựng",
                            Connectivity = "Có dây",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thiết kế mạnh mẽ cùng pin dài mang lại trải nghiệm loa Marshall Emberton 3 vô cùng khác biệt, pin lên tới 32 tiếng, chống nước IP 67, có Micro trong, sạc cực nhanh.",
                            FrequencyResponse = "20Hz - 20kHz",
                            Name = "Tai nghe Marshall Major 5",
                            Price = 4290000m,
                            Sensitivity = "105 dB",
                            SpecialFeatures = "Âm thanh chi tiết, khả năng chống ồn hiệu quả.",
                            Status = 1,
                            StockQuantity = 50,
                            SubCategoryId = 6,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 2L,
                            AccessoriesIncluded = "Cáp sạc, ốp tai",
                            Connectivity = "Có dây",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thiết kế đơn giản của tai nghe Marshall Minor IV cho phép bạn tập trung vào điều quan trọng nhất – âm nhạc. Những chiếc tai nghe này bao gồm tất cả các tính năng để bạn có thể đắm chìm trong âm thanh đặc trưng của Marshall mọi lúc mọi nơi. Mang theo hơn 30 giờ thời gian chơi không dây cùng với hộp đựng, nghĩa là bạn có hơn một ngày để đắm chìm trong âm nhạc hoặc podcast yêu thích của mình. Thêm thiết kế tai nghe chống nước , bạn sẽ tận hưởng từng nhịp điệu một cách hoàn toàn thoải mái.",
                            FrequencyResponse = "18Hz - 22kHz",
                            Name = "Tai nghe Marshall Minor 4",
                            Price = 3690000m,
                            Sensitivity = "100 dB",
                            SpecialFeatures = "Chất lượng âm thanh tuyệt vời, thiết kế tiện lợi.",
                            Status = 1,
                            StockQuantity = 70,
                            SubCategoryId = 7,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 3L,
                            AccessoriesIncluded = "Cáp kết nối, đệm tai mềm mại",
                            Connectivity = "Có dây",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe Marshall Motif II A.N.C mang đến âm thanh lớn trong môt thiết kế bỏ túi nhỏ gọn. Hộp sạc với kiểu dáng thời thượng cung cấp cho tai nghe khả năng chơi nhạc không dây lên tới 30 giờ. Mẫu tai nghe in-ear này giờ đây được trang bị công nghệ Bluetooth LE (Low Energy) cho khả năng kết nối không dây tốt hơn bao giờ hết. Với tính năng khử tiếng ồn chủ động và việc cải thiện hiệu suất lọc gió, Motif II A.N.C có thể loại bỏ tiếng ồn từ đám đông và phương tiện xung quanh, giúp bạn thả hồn vào âm nhạc mà không bị phân tâm.",
                            FrequencyResponse = "20Hz - 20kHz",
                            Name = "Tai nghe Marshall Motif 2 A.N.C",
                            Price = 5490000m,
                            Sensitivity = "102 dB",
                            SpecialFeatures = "Âm thanh vòm, micro rõ ràng.",
                            Status = 1,
                            StockQuantity = 30,
                            SubCategoryId = 7,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 4L,
                            AccessoriesIncluded = "Cáp sạc, hướng dẫn sử dụng",
                            BatteryLife = "10 giờ",
                            Connectivity = "Bluetooth",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đến với tai nghe Marshall Minor III và trải nghiệm âm thanh đặc trưng của Marshall với khả năng âm thanh chi tiết, rõ nét. Tận hưởng thời lượng pin với tổng 25 giờ sử dụng và tự do nghe nhạc không dây với chất lượng âm thanh cực tốt. Tai nghe Marshall Minor 3 được tối ưu tất cả bước sử dụng phức tạp, tất cả những gì cần làm là ghép nối với thiết bị của mình và trải nghiệm âm nhạc.",
                            FrequencyResponse = "50Hz - 20kHz",
                            Name = "Tai nghe Marshall Minor 3",
                            Price = 3390000m,
                            Sensitivity = "95 dB",
                            SpecialFeatures = "Kết nối nhanh, thời lượng pin lên đến 10 giờ.",
                            Status = 1,
                            StockQuantity = 40,
                            SubCategoryId = 7,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 5L,
                            AccessoriesIncluded = "Cáp sạc, túi đựng",
                            BatteryLife = "8 giờ",
                            Connectivity = "Jack 3.5mm",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe Marshall Mode cho ra chất lượng âm thanh mạnh mẽ chỉ trong một chiếc thiết kế nhỏ gọn. Driver cải tiến cho đầu ra nhạc chất lượng cao mà không bị biến dạng âm thanh. Thiết kế độc đáo có 4 chiếc cao su bọc ngoài đi kèm với các kích cỡ khác nhau để bạn có thể thay đổi tùy theo kích cỡ tai của mỗi người.",
                            FrequencyResponse = "55Hz - 18kHz",
                            Name = "Tai nghe Marshall Mode",
                            Price = 1290000m,
                            Sensitivity = "90 dB",
                            SpecialFeatures = "Âm bass mạnh mẽ, thiết kế di động.",
                            Status = 1,
                            StockQuantity = 60,
                            SubCategoryId = 7,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 6L,
                            AccessoriesIncluded = "Cáp nguồn, hướng dẫn sử dụng",
                            Connectivity = "Bluetooth",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe Marshall Major 4 mang thiết kế đặc trưng của Marshall cho khả năng chơi nhạc không dây lên đến 80 giờ liên tục, bổ sung thêm tính năng sạc không dây và thiết kế được cải tiến đem đến sự thoải mái vượt trội và tiện dụng hơn. Các dải âm được bổ sung tạo ra âm trầm mạnh mẽ, âm trung mượt mà và âm bổng tuyệt vời khiến cho khoảnh khắc thưởng nhạc trở nên trọn vẹn hơn bao giờ hết.",
                            FrequencyResponse = "45Hz - 19kHz",
                            Name = "Tai nghe Marshall Major 4",
                            Price = 4290000m,
                            Sensitivity = "92 dB",
                            SpecialFeatures = "Âm thanh sống động, thiết kế hiện đại.",
                            Status = 1,
                            StockQuantity = 25,
                            SubCategoryId = 6,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 24 tháng"
                        },
                        new
                        {
                            Id = 7L,
                            AccessoriesIncluded = "Hộp đựng, cáp sạc",
                            BatteryLife = "20 giờ",
                            Connectivity = "Wireless",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe không dây với công nghệ tiên tiến, thời lượng pin lên đến 20 giờ.",
                            FrequencyResponse = "20Hz - 20kHz",
                            Name = "Loa Marshall Willen 2 (Chính Hãng ASH)",
                            Price = 2990000m,
                            Sensitivity = "104 dB",
                            SpecialFeatures = "Kết nối ổn định, thời gian sử dụng lâu dài.",
                            Status = 1,
                            StockQuantity = 45,
                            SubCategoryId = 1,
                            Type = "Loa",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 8L,
                            AccessoriesIncluded = "Cáp, bộ chuyển đổi",
                            BatteryLife = "17 giờ cho mỗi lần sạc",
                            Connectivity = "Wireless",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Loa Marshall Middleton là chiếc loa di động nhỏ gọn với âm thanh mạnh mẽ và sống động mà chỉ Marshall có thể đem lại. Marshall Middleton sử dụng công nghệ True Stereophonic, một dạng âm thanh đa hướng độc đáo từ Marshall giúp bạn trải nghiệm âm thanh 360° t tuyệt vời dù ở bất kì vị trí nào trong hơn 20 giờ chơi nhạc. Đặc biệt loa Marshall Middleton tích hợp công nghệ cho phép ghép nhiều loa với nhau đem đến trải nghiệm âm thanh đa chiều. Marshall Middleton có thể được sử dụng thoải mái cả ở nhà hay ở bất kì nơi nào với các không gian khác nhau.",
                            FrequencyResponse = "19Hz - 21kHz",
                            Name = "Loa Marshall Middleton",
                            Price = 8090000m,
                            Sensitivity = "103 dB",
                            SpecialFeatures = "Âm thanh ổn định, thiết kế tiện lợi.",
                            Status = 1,
                            StockQuantity = 5,
                            SubCategoryId = 1,
                            Type = "Loa",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 9L,
                            AccessoriesIncluded = "Cáp, adapter, ốp bảo vệ",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bộ phụ kiện đa năng cho tai nghe, gồm cáp, adapter và ốp bảo vệ.",
                            Name = "Marshall Bộ Phụ Kiện Tai nghe",
                            Price = 29.99m,
                            SpecialFeatures = "Tăng cường tuổi thọ cho tai nghe, dễ sử dụng.",
                            Status = 1,
                            StockQuantity = 100,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Không bảo hành"
                        },
                        new
                        {
                            Id = 10L,
                            AccessoriesIncluded = "Túi đựng",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Túi đựng cao cấp giúp bảo vệ tai nghe khỏi va đập và trầy xước.",
                            Name = "Marshall Túi Đựng Tai nghe",
                            Price = 39.99m,
                            SpecialFeatures = "Chất liệu bền, thiết kế thời trang.",
                            Status = 1,
                            StockQuantity = 80,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Bảo hành 6 tháng"
                        },
                        new
                        {
                            Id = 11L,
                            AccessoriesIncluded = "Bộ sạc",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bộ sạc chuyên dụng cho loa Marshall, thiết kế để sạc nhanh và an toàn.",
                            Name = "Marshall Bộ Sạc Loa",
                            Price = 49.99m,
                            SpecialFeatures = "Sạc nhanh, thiết kế nhỏ gọn.",
                            Status = 1,
                            StockQuantity = 35,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Bảo hành 6 tháng"
                        },
                        new
                        {
                            Id = 12L,
                            AccessoriesIncluded = "Điều khiển từ xa",
                            Connectivity = "Wireless",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bộ điều khiển từ xa cho loa, giúp điều chỉnh âm lượng và chuyển đổi nguồn nhạc.",
                            Name = "Marshall Bộ Điều Khiển từ Xa",
                            Price = 59.99m,
                            SpecialFeatures = "Tiện lợi, dễ sử dụng, tương thích với nhiều thiết bị.",
                            Status = 1,
                            StockQuantity = 40,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 13L,
                            AccessoriesIncluded = "Cáp kết nối",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cáp kết nối chất lượng cao, đảm bảo truyền tải âm thanh mượt mà và ổn định.",
                            Name = "Marshall Cáp Kết Nối",
                            Price = 19.99m,
                            SpecialFeatures = "Bền bỉ, khả năng truyền dẫn cao.",
                            Status = 1,
                            StockQuantity = 150,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Không bảo hành"
                        },
                        new
                        {
                            Id = 14L,
                            AccessoriesIncluded = "Đế sạc",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đế sạc dành cho tai nghe không dây, cho phép sạc nhanh và an toàn.",
                            Name = "Marshall Đế Sạc Tai nghe",
                            Price = 34.99m,
                            SpecialFeatures = "Thiết kế độc đáo, sạc nhanh.",
                            Status = 1,
                            StockQuantity = 45,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Bảo hành 6 tháng"
                        },
                        new
                        {
                            Id = 15L,
                            AccessoriesIncluded = "Cáp, hướng dẫn sử dụng",
                            Connectivity = "Có dây",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hệ thống loa home theater cho trải nghiệm giải trí tuyệt vời tại gia với âm thanh vòm sống động.",
                            FrequencyResponse = "40Hz - 20kHz",
                            Name = "Marshall Hệ Thống Loa Home Theater",
                            Price = 499.99m,
                            Sensitivity = "98 dB",
                            SpecialFeatures = "Âm thanh sống động, dễ dàng lắp đặt.",
                            Status = 1,
                            StockQuantity = 20,
                            SubCategoryId = 2,
                            Type = "Loa",
                            Warranty = "Bảo hành 24 tháng"
                        },
                        new
                        {
                            Id = 16L,
                            AccessoriesIncluded = "Cáp kết nối, đệm tai",
                            Connectivity = "Có dây",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe headset gaming với micro tích hợp, mang lại âm thanh rõ ràng và trải nghiệm chơi game sống động.",
                            FrequencyResponse = "20Hz - 20kHz",
                            Name = "Marshall Tai nghe Headset Gaming",
                            Price = 159.99m,
                            Sensitivity = "103 dB",
                            SpecialFeatures = "Thiết kế chắc chắn, micro rõ ràng.",
                            Status = 1,
                            StockQuantity = 30,
                            SubCategoryId = 1,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 17L,
                            AccessoriesIncluded = "Cáp sạc, giá đỡ",
                            BatteryLife = "8 giờ",
                            Connectivity = "Bluetooth",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Loa karaoke với hiệu ứng ánh sáng độc đáo, mang lại trải nghiệm âm nhạc sôi động cho các buổi tiệc.",
                            FrequencyResponse = "45Hz - 19kHz",
                            Name = "Marshall Loa Karaoke",
                            Price = 279.99m,
                            Sensitivity = "96 dB",
                            SpecialFeatures = "Hiệu ứng ánh sáng, âm thanh mạnh mẽ.",
                            Status = 1,
                            StockQuantity = 25,
                            SubCategoryId = 2,
                            Type = "Loa",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 18L,
                            AccessoriesIncluded = "Cáp, giá đỡ, túi đựng",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bộ phụ kiện loa gồm cáp kết nối, giá đỡ và túi đựng, hỗ trợ tối đa cho trải nghiệm âm nhạc.",
                            Name = "Marshall Bộ Phụ Kiện Loa",
                            Price = 39.99m,
                            SpecialFeatures = "Thiết kế chắc chắn, dễ sử dụng.",
                            Status = 1,
                            StockQuantity = 90,
                            SubCategoryId = 3,
                            Type = "Phụ kiện",
                            Warranty = "Bảo hành 6 tháng"
                        },
                        new
                        {
                            Id = 19L,
                            AccessoriesIncluded = "Cáp kết nối, đệm tai",
                            Connectivity = "Có dây",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe studio chuyên nghiệp, cung cấp âm thanh trung thực cho việc thu âm và xử lý nhạc.",
                            FrequencyResponse = "20Hz - 20kHz",
                            Name = "Marshall Tai nghe Studio",
                            Price = 189.99m,
                            Sensitivity = "106 dB",
                            SpecialFeatures = "Âm thanh chuẩn studio, thiết kế bền bỉ.",
                            Status = 1,
                            StockQuantity = 35,
                            SubCategoryId = 1,
                            Type = "Tai nghe",
                            Warranty = "Bảo hành 12 tháng"
                        },
                        new
                        {
                            Id = 20L,
                            AccessoriesIncluded = "Cáp sạc, hướng dẫn sử dụng",
                            BatteryLife = "10 giờ",
                            Connectivity = "Bluetooth",
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Loa Dolby sử dụng công nghệ tiên tiến, mang lại trải nghiệm âm thanh sống động và mượt mà.",
                            FrequencyResponse = "40Hz - 20kHz",
                            Name = "Marshall Loa Dolby",
                            Price = 399.99m,
                            Sensitivity = "97 dB",
                            SpecialFeatures = "Công nghệ Dolby, âm thanh sống động, thiết kế hiện đại.",
                            Status = 1,
                            StockQuantity = 15,
                            SubCategoryId = 2,
                            Type = "Loa",
                            Warranty = "Bảo hành 24 tháng"
                        });
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("RatingPoint")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("SoundStore.Core.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LOA DI ĐỘNG"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LOA NGHE TRONG NHÀ"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LIMITED EDITION"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TRUE WIRELESS"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ON-EAR"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OVER-EAR"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IN-EAR"
                        });
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("SoundStore.Core.Entities.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Image", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Order", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoundStore.Core.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Product", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Rating", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.AppUser", null)
                        .WithMany("Ratings")
                        .HasForeignKey("AppUserId");

                    b.HasOne("SoundStore.Core.Entities.Product", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.SubCategory", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Transaction", b =>
                {
                    b.HasOne("SoundStore.Core.Entities.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("SoundStore.Core.Entities.Transaction", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoundStore.Core.Entities.AppUser", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("SoundStore.Core.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderDetails");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SoundStore.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Ratings");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
